backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: 'src/pages/settings/header.md'
        description: 'General Site Settings'
        fields:
          - { label: 'Global title', name: 'site_title', widget: 'string' }
          - label: 'Post Settings'
            name: posts
            widget: 'object'
            fields:
              - {
                  label: 'Number of posts on frontpage',
                  name: front_limit,
                  widget: number,
                  min: 1,
                  max: 10,
                }
              - { label: 'Default Author', name: author, widget: string }
              - { label: 'Default Thumbnail', name: thumb, widget: image, class: 'thumb', required: false }
  - name: projects
    label: Projects
    folder: src/pages/project
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Project Name", name: "title", widget: "string"}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "projectTemplate"}
      - {label: "Project Options", name: "projectOptions", widget: "select", default: "hidden", options: [{label: 'Hidden', value: 'hidden'}, {label: 'Recent Work', value: 'recentWork'}, {label: 'Other Work', value: 'otherWork'}]}
      - {label: "Logo", name: "logo", widget: image, required: false}
      - {label: "Screenshot", name: "screenshot", widget: image}
      - {label: "Vimeo ID", name: "vimeoId", widget: "string", required: false}
      - {label: "Agency", name: "agaency", widget: "string", required: false}
      - {label: "Website Link", name: "websiteLink", widget: "string", required: false}
      - {label: Skills, name: skills, widget: list, fields: [{label: Skill, name: skill, widget: string}]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "indexTemplate"}
          - {label: Title, name: title, widget: string}
      - file: "src/pages/index2.md"
        label: "Home Page2"
        name: "index2"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "indexTemplate"}
          - {label: Title, name: title, widget: string}